extends SceneTree
# tools/capture_achievements.gd
# Visual proof for the 8 achievement icons (unlocked + locked = 16 PNGs).
# Builds an 8-row x 2-col grid of TextureRect nodes on a SubViewport,
# labels each cell with the achievement id and state, screenshots to
#   screenshots/art_audit/achievements_grid.png   (1280x720)
# Must run WITHOUT --headless (rendering backend required).
#
# Note: when run via `--script` in the Godot editor, the first focusable
# TextureRect gets the editor's blue selection ring drawn around it. That
# is a debug overlay from the editor, not part of the icon. For a clean
# render, run inside a built binary or use the Pillow composite in
#   screenshots/art_audit/achievements_grid_pillow.png
# (generated by tools/build_achievement_grid.py) which has no editor
# overlay.
#
# Run:
#   godot_console.exe --path . --script res://tools/capture_achievements.gd

const ACH_DIR := "res://assets/final/achievements"
const OUTPUT_REL := "res://screenshots/art_audit/achievements_grid.png"
const VIEWPORT_SIZE := Vector2i(1280, 720)

# achievement_id, chinese_name
const ACHIEVEMENTS: Array = [
	["first_night",       "活过第一夜"],
	["first_contact",     "首次联络"],
	["recruit_nora",      "Nora 加入"],
	["recruit_elias",     "Elias 加入"],
	["all_three_allies",  "三人齐聚"],
	["reach_victor",      "接通 Victor"],
	["clear_all_nights",  "十夜生存"],
	["no_breach",         "零失守"],
]

var _vp: SubViewport
var _root: Control


func _initialize() -> void:
	_ensure_dir()
	_run.call_deferred()


func _suppress_focus_ring(node: Control) -> void:
	# Empty StyleBoxFlat = no border, no focus ring drawn
	var empty := StyleBoxFlat.new()
	empty.bg_color = Color(0, 0, 0, 0)
	empty.border_color = Color(0, 0, 0, 0)
	empty.content_margin_left = 0
	empty.content_margin_right = 0
	empty.content_margin_top = 0
	empty.content_margin_bottom = 0
	node.add_theme_stylebox_override("focus", empty)
	node.add_theme_stylebox_override("hover", empty)
	node.add_theme_stylebox_override("normal", empty)
	node.add_theme_stylebox_override("pressed", empty)


func _load_tex(filename: String) -> Texture2D:
	# Try the imported texture first, then the raw PNG. The PNG loads
	# fine in the editor before the import pass completes; the .ctex
	# path is the normal runtime path.
	var png_path: String = "%s/%s" % [ACH_DIR, filename]
	if ResourceLoader.exists(png_path, "Texture2D"):
		var t: Texture2D = load(png_path) as Texture2D
		if t != null:
			return t
	var imp_path: String = "%s/%s.import" % [ACH_DIR, filename]
	if ResourceLoader.exists(imp_path, "Texture2D"):
		var t2: Texture2D = load(imp_path) as Texture2D
		if t2 != null:
			return t2
	push_warning("missing texture: %s" % png_path)
	return null


func _ensure_dir() -> void:
	var abs_path := ProjectSettings.globalize_path(
		"res://screenshots/art_audit")
	if not DirAccess.dir_exists_absolute(abs_path):
		DirAccess.make_dir_recursive_absolute(abs_path)


func _run() -> void:
	_vp = SubViewport.new()
	_vp.size = VIEWPORT_SIZE
	_vp.transparent_bg = false
	_vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(_vp)

	_root = Control.new()
	_root.set_anchors_preset(Control.PRESET_FULL_RECT)
	_root.size = VIEWPORT_SIZE
	_root.focus_mode = Control.FOCUS_NONE
	_root.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_vp.add_child(_root)

	# background — sober ash-gray panel
	var bg := ColorRect.new()
	bg.color = Color(0.18, 0.17, 0.16, 1.0)
	bg.set_anchors_preset(Control.PRESET_FULL_RECT)
	_root.add_child(bg)

	# title bar
	var title := Label.new()
	title.text = "Last Radio — Achievement Icons (unlocked / locked)"
	title.position = Vector2(24, 18)
	title.add_theme_color_override("font_color", Color(0.95, 0.87, 0.7))
	title.add_theme_font_size_override("font_size", 22)
	_root.add_child(title)

	# column headers
	var h_unlocked := Label.new()
	h_unlocked.text = "UNLOCKED"
	h_unlocked.position = Vector2(340, 50)
	h_unlocked.add_theme_color_override("font_color", Color(0.85, 0.75, 0.55))
	h_unlocked.add_theme_font_size_override("font_size", 14)
	_root.add_child(h_unlocked)
	var h_locked := Label.new()
	h_locked.text = "LOCKED"
	h_locked.position = Vector2(700, 50)
	h_locked.add_theme_color_override("font_color", Color(0.65, 0.62, 0.58))
	h_locked.add_theme_font_size_override("font_size", 14)
	_root.add_child(h_locked)

	# grid: 8 rows. 64px icon, scaled up 4x to 256px for visual review.
	var row_y_start: int = 80
	var row_h: int = 76
	for i in range(ACHIEVEMENTS.size()):
		var ach_id: String = ACHIEVEMENTS[i][0]
		var cn_name: String = ACHIEVEMENTS[i][1]
		var y: int = row_y_start + i * row_h

		# row label (left column)
		var label := Label.new()
		label.text = "%s  ·  %s" % [ach_id, cn_name]
		label.position = Vector2(24, y + 18)
		label.add_theme_color_override("font_color",
			Color(0.92, 0.86, 0.74))
		label.add_theme_font_size_override("font_size", 13)
		label.focus_mode = Control.FOCUS_NONE
		label.mouse_filter = Control.MOUSE_FILTER_IGNORE
		_root.add_child(label)

		# unlocked cell
		var unlocked_tex: Texture2D = _load_tex("ach_%s_unlocked.png" % ach_id)
		if unlocked_tex != null:
			var tr_u := TextureRect.new()
			tr_u.texture = unlocked_tex
			tr_u.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
			tr_u.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
			tr_u.custom_minimum_size = Vector2(64, 64)
			tr_u.position = Vector2(360, y + 6)
			tr_u.size = Vector2(64, 64)
			tr_u.focus_mode = Control.FOCUS_NONE
			tr_u.mouse_filter = Control.MOUSE_FILTER_IGNORE
			_suppress_focus_ring(tr_u)
			_root.add_child(tr_u)

		# divider
		var div := ColorRect.new()
		div.color = Color(0.30, 0.28, 0.25, 1.0)
		div.position = Vector2(680, y)
		div.size = Vector2(1, row_h - 4)
		_root.add_child(div)

		# locked cell
		var locked_tex: Texture2D = _load_tex("ach_%s_locked.png" % ach_id)
		if locked_tex != null:
			var tr_l := TextureRect.new()
			tr_l.texture = locked_tex
			tr_l.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
			tr_l.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
			tr_l.custom_minimum_size = Vector2(64, 64)
			tr_l.position = Vector2(720, y + 6)
			tr_l.size = Vector2(64, 64)
			tr_l.focus_mode = Control.FOCUS_NONE
			tr_l.mouse_filter = Control.MOUSE_FILTER_IGNORE
			_suppress_focus_ring(tr_l)
			_root.add_child(tr_l)

	# footer
	var footer := Label.new()
	footer.text = ("achievements/  16 PNGs @ 64x64  ·  8 unlocked + 8 locked  "
		+ "·  locked = luminance + alpha×0.55 + slight darken")
	footer.position = Vector2(24, 700)
	footer.add_theme_color_override("font_color", Color(0.55, 0.52, 0.48))
	footer.add_theme_font_size_override("font_size", 11)
	_root.add_child(footer)

	await process_frame
	await process_frame
	# Release any default focus that the editor may have placed on the
	# first control, and force a no-focus state on the root window.
	if _root.get_window() != null:
		_root.get_window().gui_release_focus()
	await RenderingServer.frame_post_draw
	await RenderingServer.frame_post_draw

	var img: Image = _vp.get_texture().get_image()
	if img != null:
		img.save_png(OUTPUT_REL)
		print("saved %s" % OUTPUT_REL)
	else:
		print("ERROR: null image")
	quit(0)
